stages:
  - compile
  - test
  - deploy
build:
  stage: compile
  image: golang:1.21.3
  script:
    - go get -d -v
    - go build -o bin/poc-api-golang-gin-graphql -v .
test:
  stage: test
  image: golang:1.21.3
  script:
    - go test service/*.go
staging:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=poc-api-golang-video-app --api-key=$HEROKU_API_KEY
  environment:
    name: Staging
    url: https://poc-api-golang-video-app.herokuapp.com/
  only:
    - ci-cd
